# Generated by Django 3.2.5 on 2021-07-24 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='vehicle type')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'db_table': 'types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='make')),
                ('model', models.CharField(db_index=True, max_length=100, verbose_name='model')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='descriptions exist', verbose_name='short description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='price USD')),
                ('image', models.ImageField(blank=True, upload_to='cars', verbose_name='upload image')),
                ('power', models.CharField(max_length=20, verbose_name='engine power')),
                ('battery', models.CharField(max_length=20, verbose_name='battery energy')),
                ('range', models.CharField(max_length=20, verbose_name='pure electric range')),
                ('charging_time', models.CharField(max_length=20, verbose_name='charging time')),
                ('type_of_battery', models.CharField(default='lithium-ion', max_length=100, verbose_name='type of battery')),
                ('from_0_to_100', models.CharField(max_length=20, verbose_name='0 to 100 km/h')),
                ('max_speed', models.CharField(max_length=20, verbose_name='max speed')),
                ('torque', models.CharField(max_length=20, verbose_name='torque')),
                ('type_of_drive', models.CharField(blank=True, max_length=20, verbose_name='type of drive')),
                ('in_storage', models.PositiveIntegerField(default=1, verbose_name='in storage')),
                ('available', models.BooleanField(default=True, verbose_name='vehicle available')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='shop.type')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['make', 'model', 'time_create'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
